version: '3.8'

services:
  robot-server:
    build:
      context: .
      dockerfile: Dockerfile
      #platform: linux/amd64
    image: robot-server:latest
    container_name: robot-server
    ports:
      - "7968:7968"
    environment:
      - NODE_ENV=production
      - PORT=7968
      - HOST=0.0.0.0
      - UPLOAD_DIR=/app/uploads
      - CORS_ORIGINS=*
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - LOG_LEVEL=info
      - WS_PATH=/socket.io
      - WS_CORS_ORIGINS=*
    # env_file:
    #   - .env
    volumes:
      - /home/vmadmin/robot_server/uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - robot-network

networks:
  robot-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local